### ISSUE TITLE
Request to upload the code used for the Analysis of convolution results.

### ISSUE THREAD

**Issue by VaticanCameos99** [GIST-CSBL/DeepConv-DTI#10]
I read the [DeepConv-DTI paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007129#pcbi-1007129-g007). The analysis of the convolution results to get the potential ligand binding sites interests me but I have a few doubts about the random generation of 128 convolution results. Please can you upload the code for it?

**Comment by dlsrnsi** [comment]
Here is code for generation of covolution results.
```
def count_binding_region_in_pooled_with_rand(binding_region, protein_length, window_size, filter_size=128):
    rand_int = np.random.randint(low=0, high=protein_length, size=filter_size)
    queried_regions = [range(j, j+window_size) for j in rand_int]
    count = sum([sum([binding_ind in queried_region for binding_ind in binding_region]) for queried_region in queried_regions])
    return count
```
