### ISSUE TITLE
Is drug_features a list of strings?

### ISSUE THREAD

**Issue by VaticanCameos99** [GIST-CSBL/DeepConv-DTI#11]
I'm new to tf so I may have misunderstood something in the code.

In DeepConvDTI.py, the line where we extract the drug features is as follows:

`    drug_feature = np.stack(dti_df[drug_vec].map(lambda fp: fp.split("\t")))
`
Which makes it a list of strings. I checked the inputs before calling self.model_t.predict() and the drug feature remains unchanged. Does this mean we are giving a list of strings to the drug's pipeline? Or does tf.keras.Model() modify it implicitly?

**Comment by dlsrnsi** [comment]
Keras implicitly change list of string to tensor of float when it is possible.

```
from keras.models import Model
from keras.layers import Input, Add
import numpy as np

input_layer = Input(shape=(2,))
output_layer = Add()([input_layer, input_layer])
model = Model(input=input_layer, output=output_layer)
data = np.array([["1", "0"]])
model.predict(data)
```

result is

`array([[2., 0.]], dtype=float32)`
