### ISSUE TITLE
Inquiry about SAE code

### ISSUE THREAD

**Issue by kexinhuang12345** [GIST-CSBL/DeepConv-DTI#2]
Hi,

I saw on your paper, you replicate the result of SAE MFDR. I am wondering if you have any plan to share the code to the community for comparison? Thank you!

**Comment by dlsrnsi** [comment]
Sorry to reply, we are not sure about license of their code from publication. Thus, we're not gonna share the code of MFDR. But for giving hint of their code, use `activity_regularizer` at keras layer to build SAE.
