### ISSUE TITLE
Error while running the toy_examples

### ISSUE THREAD

**Issue by rebirthjin** [GIST-CSBL/DeepConv-DTI#5]
Hello, I'm running DeepConv-DTI for toy_examples, but it was getting an error message in process of prediction model. 

    python predict_with_model.py ./model.model -n predict -i ./toy_examples/test_dataset/test_dti.csv -d ./toy_examples/test_dataset/test_compound.csv -t ./toy_examples/test_dataset/test_protein.csv -v Convolution -l 2500 -V morgan_fp_r2 -L 2048 -W -o test_result.csv

    Traceback (most recent call last): 
     File "predict_with_model.py", line 118, in <module>
     d_splitted = np.array_split(prediction_dic["drug_feature"], N)
    File "<__array_function__ internals>", line 6, in array_split
    File "/Data1/program/anaconda3/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 761, in array_split
    raise ValueError('number sections must be larger than 0.')

When I showed the variable, "N" indicated zero. 

    N = int(prediction_dic["drug_feature"].shape[0]/50)

In the code, ###prediction_dic["drug_feature"].shape[0] is 20.

Please, any help! 
Thank you

**Comment by dlsrnsi** [comment]
Hello!
As you wrote in issue, N indicated 0, which is the number of splitted array, causing error.

50 is too large, resulting N to be set as 0. I think we can solve it by using ceiling function.

Would you try this one?

`N = np.ceil(prediction_dic["drug_feature"].shape[0]/50)`

Thank you for raising issue for it.

**Comment by rebirthjin** [comment]
As your comment, I changed code by using ceiling function.
It is finished,properly!
Thank you for kind response.
