### ISSUE TITLE
Can i get the full dataset(training/test dataset)? 

### ISSUE THREAD

**Issue by Parksoojeong** [GIST-CSBL/DeepConv-DTI#6]

**Comment by dlsrnsi** [comment]
Sorry for late reply.
Regarding your inquiry, we are currently not distributing the dataset used in training, validating, and testing the model because of the publication schedule of the other study in our lab.
We feel sorry that we cannot be more positive about your request.

**Comment by Parksoojeong** [comment]
안녕하세요. 답변 감사합니다.
 
한가지 궁금한 내용이 있어서 보내드립니다.^^
데이터 중에 compound "morgan_fp_r2", protein " AAComposition" 에 대한 컬럼 값이 있습니다.
이 내용 데이터의 로직 또는 출처를 알고 싶은데 나와 있지 않아서 문의를 드립니다.
  
답변 부탁드립니다.
 
-----Original Message-----

**Comment by dlsrnsi** [comment]
For `morgan_fp_r2` in compound columns, 
we used RDKit to generate morgan fingerprint with radius 2 and nBits 2048.
In practice, please follow this tutorial 
https://www.rdkit.org/docs/GettingStartedInPython.html#morgan-fingerprints-circular-fingerprints

For `AAComposition` in protein columns,
we used `pydpi` to generate protein composition descriptor which describe proportion of amino acids, bipeptide and tripeptides.
[DeepDTI](https://pubs.acs.org/doi/full/10.1021/acs.jproteome.6b00618) used those descriptors as protein representation.

p.s Please write issues as English for other users.
